"""Phase 2 candidate fitness — phased evaluation for the four-phase worker.

Two entry points, called in sequence by the worker:

    Phase A — `phase_a_generate(spec, pipeline, db, ...)`
        Gemma3-12B is loaded. Derive the steering direction, run 8 injected
        + 4 control probes, store all 12 raw responses in `pending_responses`.
        No judge calls.

    Phase B — `phase_b_judge(candidate_id, judge, db, ...)`
        Judge model is loaded (Gemma is not). Score every pending response,
        insert into `evaluations`, compute fitness, write to `fitness_scores`,
        delete the pending rows, mark the candidate `done`.

The `pending_responses` rows are the durable hand-off: a crash between A
and B doesn't lose work — the worker drains orphan pending rows on
startup before generating new ones.

Fitness math (unchanged from prior pipeline):

    fitness = (det_weight * detection_rate + ident_weight * identification_rate)
              * fpr_penalty * coherence_rate
    where fpr_penalty = max(0, 1 - 5 * fpr)

    Default mode:           det_weight=1.0, ident_weight=15.0
    ident_prioritized mode: det_weight=0.5, ident_weight=30.0  (ADR-018)

Mode is read from `spec.fitness_mode` first, then `FITNESS_MODE` env var,
then defaults to "default". Strategy generators set per-spec mode so a
mixed queue scores each candidate under whatever mode the strategy that
generated it intended.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import torch

from .bridge import DetectionPipeline
from .db import ResultsDB
from .judges.base import Judge

DEFAULT_N_HELD_OUT = 8
DEFAULT_N_CONTROLS = 4

# Phase 2h: precomputed fault-line directions. Loaded once and cached so
# every Phase A probe reuses the same tensor without disk I/O.
_FAULT_LINE_DIRECTIONS_CACHE: Optional[dict] = None


def _load_fault_line_direction(
    fault_line: str,
    device,
    dtype,
) -> "torch.Tensor":
    """Load the precomputed (3840,) fault-line steering direction.

    Reads data/sae_features/fault_line_directions.pt on first call,
    caches the dict in-process, returns the requested fault line's
    direction moved to the model's device + dtype.
    """
    global _FAULT_LINE_DIRECTIONS_CACHE
    if _FAULT_LINE_DIRECTIONS_CACHE is None:
        path = (
            Path(__file__).resolve().parent.parent
            / "data" / "sae_features" / "fault_line_directions.pt"
        )
        if not path.exists():
            raise FileNotFoundError(
                f"Fault-line directions file missing: {path}\n"
                "Run `python scripts/build_fault_line_directions.py` first."
            )
        # weights_only=False because the payload contains plain dicts/strs
        # alongside tensors; the file is generated by our own script and
        # not user-supplied.
        _FAULT_LINE_DIRECTIONS_CACHE = torch.load(path, weights_only=False)
    payload = _FAULT_LINE_DIRECTIONS_CACHE
    directions = payload.get("directions") or {}
    if fault_line not in directions:
        raise KeyError(
            f"fault line {fault_line!r} not found in directions file. "
            f"Available: {sorted(directions.keys())}"
        )
    direction = directions[fault_line]["direction"]
    return direction.detach().clone().to(device=device, dtype=dtype)


@dataclass
class CandidateSpec:
    """A candidate steering direction's full specification.

    Three derivation methods:

    - ``derivation_method="mean_diff"`` (Phase 1, historical): derive a
      steering vector for the single concept word ``concept`` by
      mean-differencing its activations against ``baseline_n`` random
      baseline words.

    - ``derivation_method="contrast_pair"`` (Phase 2b/2d, historical):
      derive a direction from two LISTS of short example sentences.
      Retired in Phase 2g for lexical-confound reasons; kept here so
      historical rows still load.

    - ``derivation_method="sae_feature_space_mean_diff"`` (Phase 2h,
      active): mean-difference of SAE-encoded activations between a
      positive and a control prompt corpus, projected back to the
      residual stream via W_dec. ``sae_fault_line`` identifies which
      Capraro fault-line corpus the direction was built from. The
      direction itself isn't stored on the spec — it's loaded by index
      from data/sae_features/fault_line_directions.pt at Phase A time.
      ``sae_auto_interp`` carries the fault line's judge target text.
    """
    id: str
    strategy: str
    concept: str
    layer_idx: int
    target_effective: float
    derivation_method: str = "mean_diff"
    baseline_n: int = 32
    notes: str = ""
    # Only populated when derivation_method == "contrast_pair":
    #   {"axis": str, "positive": list[str], "negative": list[str]}
    contrast_pair: Optional[dict] = None
    # Per-candidate fitness mode (ADR-018). Strategies set this:
    #   "default" — Phase 1: (det + 15·ident) · fpr_penalty · coh
    #   "ident_prioritized" — Phase 2d: 0.5·det + 30·ident
    #   "sae_aware" — Phase 2g/2h: (det + 15·ident_conceptual + 3·ident_lexical)
    # Falls back to FITNESS_MODE env var if unset, then to "default".
    fitness_mode: Optional[str] = None
    # Historical: which LLM proposer produced this spec. Phase 2h has no
    # proposer (directions are built once from prompt corpora). Kept for
    # legacy rows so the web UI's substrate badge resolves provenance
    # for historical contrast_pair candidates.
    proposer_model: Optional[str] = None
    # Only populated when derivation_method == "sae_feature_space_mean_diff":
    sae_release: Optional[str] = None       # e.g. "google/gemma-scope-2-12b-it"
    sae_id: Optional[str] = None            # e.g. "resid_post/layer_31_width_262k_l0_medium"
    sae_auto_interp: Optional[str] = None   # judge-target description
    sae_fault_line: Optional[str] = None    # which Capraro fault line corpus

    @classmethod
    def from_dict(cls, d: dict) -> "CandidateSpec":
        return cls(
            id=d["id"],
            strategy=d.get("strategy", "unknown"),
            concept=d["concept"],
            layer_idx=int(d["layer_idx"]),
            target_effective=float(d["target_effective"]),
            derivation_method=d.get("derivation_method", "mean_diff"),
            baseline_n=int(d.get("baseline_n", 32)),
            notes=d.get("notes", ""),
            contrast_pair=d.get("contrast_pair"),
            fitness_mode=d.get("fitness_mode"),
            proposer_model=d.get("proposer_model"),
            sae_release=d.get("sae_release"),
            sae_id=d.get("sae_id"),
            sae_auto_interp=d.get("sae_auto_interp"),
            sae_fault_line=d.get("sae_fault_line"),
        )

    def to_dict(self) -> dict:
        out = {
            "id": self.id,
            "strategy": self.strategy,
            "concept": self.concept,
            "layer_idx": self.layer_idx,
            "target_effective": self.target_effective,
            "derivation_method": self.derivation_method,
            "baseline_n": self.baseline_n,
            "notes": self.notes,
        }
        if self.contrast_pair is not None:
            out["contrast_pair"] = self.contrast_pair
        if self.fitness_mode is not None:
            out["fitness_mode"] = self.fitness_mode
        if self.proposer_model is not None:
            out["proposer_model"] = self.proposer_model
        for f in ("sae_release", "sae_id",
                  "sae_auto_interp", "sae_fault_line"):
            v = getattr(self, f)
            if v is not None:
                out[f] = v
        return out


@dataclass
class FitnessResult:
    score: float
    detection_rate: float
    identification_rate: float
    fpr: float
    coherence_rate: float
    n_held_out: int
    n_controls: int
    components: dict


def _candidate_seed(spec: CandidateSpec, base_seed: int) -> int:
    id_seed = int(hashlib.sha256(spec.id.encode()).hexdigest()[:8], 16)
    return base_seed + id_seed


def spec_hash(spec: CandidateSpec, abliteration_mode: str = "vanilla") -> str:
    """Stable dedup key for the candidates table.

    Covers every (derivation_method)'s identity-defining fields:

    - ``mean_diff`` (Phase 1 historical): concept + layer + effective + method.
    - ``contrast_pair`` (Phase 2 historical): adds positive/negative pole
      sentences; replication-tagged rationales also included.
    - ``sae_feature_space_mean_diff`` (Phase 2h, active): adds the SAE
      identity + the fault-line tag. Different fault lines → different
      directions → different hashes.

    `abliteration_mode` defaults to ``"vanilla"`` so legacy hashes stay
    bit-identical with pre-2026-04-24 entries; only non-vanilla suffixes.
    """
    payload = (
        f"{spec.concept}|{spec.layer_idx}|{spec.target_effective:.1f}"
        f"|{spec.derivation_method}"
    )
    if spec.derivation_method == "contrast_pair" and spec.contrast_pair is not None:
        pos = "|".join(spec.contrast_pair.get("positive", []))
        neg = "|".join(spec.contrast_pair.get("negative", []))
        payload += f"|pos:{pos}|neg:{neg}"
        rationale = spec.contrast_pair.get("rationale", "") or ""
        if rationale.startswith("[replication-of-"):
            payload += f"|rep:{rationale[:80]}"
    elif spec.derivation_method == "sae_feature_space_mean_diff":
        payload += (
            f"|sae:{spec.sae_release}|{spec.sae_id}|fl:{spec.sae_fault_line}"
        )
    if abliteration_mode and abliteration_mode != "vanilla":
        payload += f"|abl:{abliteration_mode}"
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


# ----------------------------------------------------------------------
# Phase A — generate responses (Gemma loaded)
# ----------------------------------------------------------------------

def phase_a_generate(
    spec: CandidateSpec,
    pipeline: DetectionPipeline,
    db: ResultsDB,
    held_out_concepts: list[str],
    control_concepts: list[str],
    n_held_out: int = DEFAULT_N_HELD_OUT,
    n_controls: int = DEFAULT_N_CONTROLS,
    rng_seed: Optional[int] = None,
    verbose: bool = True,
) -> dict:
    """Generate Gemma responses for `spec` and stash them in pending_responses.

    No judge call here — responses are queued for Phase B. Returns a summary
    dict so the worker can log progress.

    Idempotent: if `spec.id` already has rows in pending_responses, we trust
    them (crash recovery) and skip generation.
    """
    base_seed = rng_seed if rng_seed is not None else 0
    candidate_seed = _candidate_seed(spec, base_seed)

    if db.count_pending_responses(spec.id) > 0:
        if verbose:
            print(
                f"    [phase_a] {spec.id} already has pending responses, skipping",
                flush=True,
            )
        return {
            "candidate_id": spec.id,
            "skipped": True,
            "reason": "already_pending",
            "n_pending": db.count_pending_responses(spec.id),
        }

    rng = random.Random(candidate_seed)
    held_out = [c for c in held_out_concepts if c.lower() != spec.concept.lower()]
    rng.shuffle(held_out)
    held_out = held_out[:n_held_out]

    controls = [c for c in control_concepts if c.lower() != spec.concept.lower()]
    rng.shuffle(controls)
    controls = controls[:n_controls]

    # Suspend abliteration hooks during direction derivation (ADR-014).
    suspend = (
        pipeline.abliteration_ctx.suspended()
        if getattr(pipeline, "abliteration_ctx", None) is not None
        and pipeline.abliteration_ctx.installed
        else contextlib.nullcontext()
    )
    with suspend:
        if spec.derivation_method == "contrast_pair":
            if spec.contrast_pair is None:
                raise ValueError(
                    f"Candidate {spec.id}: derivation_method='contrast_pair' "
                    "but contrast_pair field is None"
                )
            from .paper import extract_concept_vector
            direction = extract_concept_vector(
                model=pipeline.model,
                positive_prompts=spec.contrast_pair["positive"],
                negative_prompts=spec.contrast_pair["negative"],
                layer_idx=spec.layer_idx,
                token_idx=-1,
                normalize=False,
            )
        elif spec.derivation_method == "sae_feature_space_mean_diff":
            if spec.sae_fault_line is None:
                raise ValueError(
                    f"Candidate {spec.id}: derivation_method="
                    f"'sae_feature_space_mean_diff' but sae_fault_line is None"
                )
            direction = _load_fault_line_direction(
                fault_line=spec.sae_fault_line,
                device=pipeline.model.device,
                dtype=pipeline.model.dtype,
            )
        else:
            direction = pipeline.derive(
                concept=spec.concept, layer_idx=spec.layer_idx
            )

    norm = float(direction.norm().item())
    alpha = spec.target_effective / max(norm, 1e-6)

    if spec.derivation_method == "contrast_pair":
        prompt_style = "open"
    elif spec.derivation_method == "sae_feature_space_mean_diff":
        prompt_style = "paper"
    else:
        prompt_style = "paper"

    if verbose:
        print(
            f"    derive: concept={spec.concept!r} L={spec.layer_idx} "
            f"||dir||={norm:.4g} alpha={alpha:.4g} prompt={prompt_style}",
            flush=True,
        )

    # Pre-compute contrast-pair / SAE fields once so they don't get
    # re-stringified on every probe row.
    if spec.derivation_method == "contrast_pair":
        contrast_axis = spec.contrast_pair["axis"]
        contrast_description = (
            spec.notes or spec.contrast_pair.get("description") or ""
        )
        contrast_positive = spec.contrast_pair["positive"]
        contrast_negative = spec.contrast_pair["negative"]
        judge_concept = None
    elif spec.derivation_method == "sae_feature_space_mean_diff":
        # Phase 2h: judge against the fault-line description (e.g.
        # "causation, one event making another happen"). The judge will
        # emit identification_type ∈ {conceptual, lexical_fallback, none}.
        contrast_axis = None
        contrast_description = None
        contrast_positive = None
        contrast_negative = None
        judge_concept = spec.sae_auto_interp or spec.concept
    else:
        contrast_axis = None
        contrast_description = None
        contrast_positive = None
        contrast_negative = None
        judge_concept = spec.concept

    n_inj = 0
    n_ctrl = 0

    # Injected probes
    for c in held_out:
        trial_seed = candidate_seed + int(
            hashlib.sha256(f"{spec.id}|{c}".encode()).hexdigest()[:8], 16
        )
        torch.manual_seed(trial_seed % (2**31))
        trial = pipeline.run_injected(
            concept=c,
            direction=direction,
            layer_idx=spec.layer_idx,
            strength=alpha,
            trial_number=1,
            max_new_tokens=120,
            judge_concept=spec.concept,
            prompt_style=prompt_style,
            run_judge=False,
        )
        db.insert_pending_response(
            candidate_id=spec.id,
            eval_concept=c,
            injected=True,
            alpha=alpha,
            direction_norm=norm,
            response=trial.response,
            derivation_method=spec.derivation_method,
            judge_concept=judge_concept,
            contrast_axis=contrast_axis,
            contrast_description=contrast_description,
            contrast_positive=contrast_positive,
            contrast_negative=contrast_negative,
        )
        n_inj += 1
        if verbose:
            print(f"      gen  inj  {c}", flush=True)

    # Control probes
    for c in controls:
        trial_seed = candidate_seed + int(
            hashlib.sha256(f"{spec.id}|ctrl|{c}".encode()).hexdigest()[:8], 16
        )
        torch.manual_seed(trial_seed % (2**31))
        trial = pipeline.run_control(
            concept=c,
            trial_number=1,
            max_new_tokens=120,
            prompt_style=prompt_style,
            run_judge=False,
        )
        db.insert_pending_response(
            candidate_id=spec.id,
            eval_concept=c,
            injected=False,
            alpha=0.0,
            direction_norm=0.0,
            response=trial.response,
            derivation_method=spec.derivation_method,
            judge_concept=judge_concept,
            contrast_axis=contrast_axis,
            contrast_description=contrast_description,
            contrast_positive=contrast_positive,
            contrast_negative=contrast_negative,
        )
        n_ctrl += 1
        if verbose:
            print(f"      gen  ctrl {c}", flush=True)

    return {
        "candidate_id": spec.id,
        "skipped": False,
        "n_inj": n_inj,
        "n_ctrl": n_ctrl,
        "norm": norm,
        "alpha": alpha,
        "prompt_style": prompt_style,
        "concepts_held_out": held_out,
        "concepts_controls": controls,
    }


# ----------------------------------------------------------------------
# Phase B — judge responses (judge loaded)
# ----------------------------------------------------------------------

def phase_b_judge(
    candidate_id: str,
    judge: Judge,
    db: ResultsDB,
    *,
    abliteration_mode: str = "vanilla",
    verbose: bool = True,
) -> FitnessResult:
    """Score `candidate_id`'s pending responses and finalize fitness.

    Reads from `pending_responses`, calls the judge per row, inserts into
    `evaluations`, computes fitness, writes to `fitness_scores`, deletes
    the pending rows, marks the candidate `status='done'`.
    """
    pending = db.get_pending_responses(candidate_id)
    if not pending:
        raise ValueError(
            f"phase_b_judge: no pending responses for candidate_id={candidate_id!r}"
        )

    cand_row = db.get_candidate(candidate_id)
    if cand_row is None:
        raise ValueError(f"phase_b_judge: candidate {candidate_id!r} missing from DB")
    spec_dict = json.loads(cand_row["spec_json"])
    spec_fitness_mode = spec_dict.get("fitness_mode")

    judge_model_tag = (
        getattr(judge, "model", None)
        or getattr(judge, "model_tag", None)
        or "unknown"
    )

    n_inj = n_det = n_ident = n_coh = 0
    n_ident_conceptual = n_ident_lexical = 0
    n_ctrl = n_fp = 0

    for row in pending:
        if row["derivation_method"] == "contrast_pair":
            jr = judge.score_contrast_pair(
                response=row["response"],
                axis=row["contrast_axis"] or "",
                description=row["contrast_description"] or "",
                positive=row["contrast_positive"] or [],
                negative=row["contrast_negative"] or [],
            )
        elif row["derivation_method"] == "sae_feature_space_mean_diff":
            # Phase 2h judge call: emits identification_type ∈
            # {conceptual, lexical_fallback, none}. Same prompt as the
            # Phase 2g score_sae_feature call — just renamed input
            # framing because we're now grading against a fault-line
            # description rather than a single SAE feature's auto-interp.
            jr = judge.score_sae_feature(
                response=row["response"],
                auto_interp=row["judge_concept"] or "",
            )
        else:
            jr = judge.score_detection(
                row["response"], row["judge_concept"] or ""
            )

        ident_type = getattr(jr, "identification_type", None)

        db.record_evaluation(
            candidate_id=candidate_id,
            eval_concept=row["eval_concept"],
            injected=row["injected"],
            alpha=row["alpha"],
            direction_norm=row["direction_norm"],
            response=row["response"],
            detected=jr.detected,
            identified=jr.identified,
            coherent=jr.coherent,
            judge_model=judge_model_tag,
            judge_reasoning=jr.reasoning,
        )

        if row["injected"]:
            n_inj += 1
            if jr.coherent:
                n_coh += 1
                if jr.detected:
                    n_det += 1
                if jr.identified:
                    n_ident += 1
                if ident_type == "conceptual":
                    n_ident_conceptual += 1
                elif ident_type == "lexical_fallback":
                    n_ident_lexical += 1
        else:
            n_ctrl += 1
            if jr.detected:
                n_fp += 1

        if verbose:
            inj_tag = "inj" if row["injected"] else "ctrl"
            ident_label = f" [{ident_type}]" if ident_type else ""
            print(
                f"      judge {inj_tag} {row['eval_concept']:<14} "
                f"det={int(jr.detected)} ident={int(jr.identified)}{ident_label} "
                f"coh={int(jr.coherent)}",
                flush=True,
            )

    detection_rate = n_det / n_inj if n_inj else 0.0
    identification_rate = n_ident / n_inj if n_inj else 0.0
    ident_conceptual_rate = n_ident_conceptual / n_inj if n_inj else 0.0
    ident_lexical_rate = n_ident_lexical / n_inj if n_inj else 0.0
    fpr = n_fp / n_ctrl if n_ctrl else 0.0
    coherence_rate = n_coh / n_inj if n_inj else 0.0

    fpr_penalty = max(0.0, 1.0 - 5.0 * fpr)
    fitness_mode = spec_fitness_mode or os.environ.get("FITNESS_MODE", "default")
    if fitness_mode == "sae_aware":
        # Phase 2g: split identification into conceptual (heavy) and
        # lexical_fallback (small) so hill-climbing drifts toward
        # sub-lexical conceptual access where it exists.
        det_weight = 1.0
        ident_weight = 15.0  # weight on conceptual; lexical gets 3.0
        ident_lexical_weight = 3.0
        ident_bonus = (
            ident_weight * ident_conceptual_rate
            + ident_lexical_weight * ident_lexical_rate
        )
        score = (det_weight * detection_rate + ident_bonus) * fpr_penalty * coherence_rate
    elif fitness_mode == "ident_prioritized":
        det_weight = 0.5
        ident_weight = 30.0
        ident_lexical_weight = 0.0
        ident_bonus = ident_weight * identification_rate
        score = (det_weight * detection_rate + ident_bonus) * fpr_penalty * coherence_rate
    else:
        fitness_mode = "default"
        det_weight = 1.0
        ident_weight = 15.0
        ident_lexical_weight = 0.0
        ident_bonus = ident_weight * identification_rate
        score = (det_weight * detection_rate + ident_bonus) * fpr_penalty * coherence_rate

    components = {
        "detection_rate": detection_rate,
        "identification_rate": identification_rate,
        "ident_conceptual_rate": ident_conceptual_rate,
        "ident_lexical_rate": ident_lexical_rate,
        "fpr": fpr,
        "coherence_rate": coherence_rate,
        "fpr_penalty": fpr_penalty,
        "ident_bonus": ident_bonus,
        "fitness_mode": fitness_mode,
        "det_weight": det_weight,
        "ident_weight": ident_weight,
        "ident_lexical_weight": ident_lexical_weight,
        "abliteration_mode": abliteration_mode,
        "judge_model": judge_model_tag,
        "n_held_out_tested": n_inj,
        "n_controls_tested": n_ctrl,
    }

    db.record_fitness(
        candidate_id=candidate_id,
        score=score,
        detection_rate=detection_rate,
        identification_rate=identification_rate,
        fpr=fpr,
        coherence_rate=coherence_rate,
        n_held_out=n_inj,
        n_controls=n_ctrl,
        components_json=json.dumps(components),
    )

    db.delete_pending_responses(candidate_id)
    db.set_candidate_status(candidate_id, "done")

    if verbose:
        print(
            f"    fitness: score={score:.3f}  "
            f"det={detection_rate:.2%} fpr={fpr:.2%} coh={coherence_rate:.2%}",
            flush=True,
        )

    return FitnessResult(
        score=score,
        detection_rate=detection_rate,
        identification_rate=identification_rate,
        fpr=fpr,
        coherence_rate=coherence_rate,
        n_held_out=n_inj,
        n_controls=n_ctrl,
        components=components,
    )


# ----------------------------------------------------------------------
# Eval-set loader (used by the worker at startup)
# ----------------------------------------------------------------------

def load_eval_sets(
    held_out_path: Path,
    control_path: Optional[Path] = None,
) -> tuple[list[str], list[str]]:
    """Load held-out and control concept lists. Controls default to held-out."""
    held_out = json.loads(Path(held_out_path).read_text())["concepts"]
    if control_path is None:
        controls = held_out
    else:
        controls = json.loads(Path(control_path).read_text())["concepts"]
    return held_out, controls
